/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProSvjRouteImport } from './routes/pro-svj'
import { Route as ProSpravceRouteImport } from './routes/pro-spravce'
import { Route as OchranaSoukromiRouteImport } from './routes/ochrana-soukromi'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CenikRouteImport } from './routes/cenik'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SluzbyIndexRouteImport } from './routes/sluzby/index'
import { Route as SluzbyCisteniVzduchovychSachetRouteImport } from './routes/sluzby/cisteni-vzduchovych-sachet'

const ProSvjRoute = ProSvjRouteImport.update({
  id: '/pro-svj',
  path: '/pro-svj',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSpravceRoute = ProSpravceRouteImport.update({
  id: '/pro-spravce',
  path: '/pro-spravce',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaSoukromiRoute = OchranaSoukromiRouteImport.update({
  id: '/ochrana-soukromi',
  path: '/ochrana-soukromi',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CenikRoute = CenikRouteImport.update({
  id: '/cenik',
  path: '/cenik',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyIndexRoute = SluzbyIndexRouteImport.update({
  id: '/sluzby/',
  path: '/sluzby/',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyCisteniVzduchovychSachetRoute =
  SluzbyCisteniVzduchovychSachetRouteImport.update({
    id: '/sluzby/cisteni-vzduchovych-sachet',
    path: '/sluzby/cisteni-vzduchovych-sachet',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/cookies': typeof CookiesRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/ochrana-soukromi': typeof OchranaSoukromiRoute
  '/pro-spravce': typeof ProSpravceRoute
  '/pro-svj': typeof ProSvjRoute
  '/sluzby/cisteni-vzduchovych-sachet': typeof SluzbyCisteniVzduchovychSachetRoute
  '/sluzby/': typeof SluzbyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/cookies': typeof CookiesRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/ochrana-soukromi': typeof OchranaSoukromiRoute
  '/pro-spravce': typeof ProSpravceRoute
  '/pro-svj': typeof ProSvjRoute
  '/sluzby/cisteni-vzduchovych-sachet': typeof SluzbyCisteniVzduchovychSachetRoute
  '/sluzby': typeof SluzbyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/cookies': typeof CookiesRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/ochrana-soukromi': typeof OchranaSoukromiRoute
  '/pro-spravce': typeof ProSpravceRoute
  '/pro-svj': typeof ProSvjRoute
  '/sluzby/cisteni-vzduchovych-sachet': typeof SluzbyCisteniVzduchovychSachetRoute
  '/sluzby/': typeof SluzbyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cenik'
    | '/cookies'
    | '/kontakt'
    | '/o-nas'
    | '/ochrana-soukromi'
    | '/pro-spravce'
    | '/pro-svj'
    | '/sluzby/cisteni-vzduchovych-sachet'
    | '/sluzby/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cenik'
    | '/cookies'
    | '/kontakt'
    | '/o-nas'
    | '/ochrana-soukromi'
    | '/pro-spravce'
    | '/pro-svj'
    | '/sluzby/cisteni-vzduchovych-sachet'
    | '/sluzby'
  id:
    | '__root__'
    | '/'
    | '/cenik'
    | '/cookies'
    | '/kontakt'
    | '/o-nas'
    | '/ochrana-soukromi'
    | '/pro-spravce'
    | '/pro-svj'
    | '/sluzby/cisteni-vzduchovych-sachet'
    | '/sluzby/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CenikRoute: typeof CenikRoute
  CookiesRoute: typeof CookiesRoute
  KontaktRoute: typeof KontaktRoute
  ONasRoute: typeof ONasRoute
  OchranaSoukromiRoute: typeof OchranaSoukromiRoute
  ProSpravceRoute: typeof ProSpravceRoute
  ProSvjRoute: typeof ProSvjRoute
  SluzbyCisteniVzduchovychSachetRoute: typeof SluzbyCisteniVzduchovychSachetRoute
  SluzbyIndexRoute: typeof SluzbyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pro-svj': {
      id: '/pro-svj'
      path: '/pro-svj'
      fullPath: '/pro-svj'
      preLoaderRoute: typeof ProSvjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-spravce': {
      id: '/pro-spravce'
      path: '/pro-spravce'
      fullPath: '/pro-spravce'
      preLoaderRoute: typeof ProSpravceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-soukromi': {
      id: '/ochrana-soukromi'
      path: '/ochrana-soukromi'
      fullPath: '/ochrana-soukromi'
      preLoaderRoute: typeof OchranaSoukromiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenik': {
      id: '/cenik'
      path: '/cenik'
      fullPath: '/cenik'
      preLoaderRoute: typeof CenikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby/': {
      id: '/sluzby/'
      path: '/sluzby'
      fullPath: '/sluzby/'
      preLoaderRoute: typeof SluzbyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby/cisteni-vzduchovych-sachet': {
      id: '/sluzby/cisteni-vzduchovych-sachet'
      path: '/sluzby/cisteni-vzduchovych-sachet'
      fullPath: '/sluzby/cisteni-vzduchovych-sachet'
      preLoaderRoute: typeof SluzbyCisteniVzduchovychSachetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CenikRoute: CenikRoute,
  CookiesRoute: CookiesRoute,
  KontaktRoute: KontaktRoute,
  ONasRoute: ONasRoute,
  OchranaSoukromiRoute: OchranaSoukromiRoute,
  ProSpravceRoute: ProSpravceRoute,
  ProSvjRoute: ProSvjRoute,
  SluzbyCisteniVzduchovychSachetRoute: SluzbyCisteniVzduchovychSachetRoute,
  SluzbyIndexRoute: SluzbyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
